### ISSUE TITLE
Latest release changed the minimum Perl to 5.12

### ISSUE THREAD

**Issue by autarch** [rjbs/Getopt-Long-Descriptive#40]
The `Makefile.PL` changed to say `use 5.12` instead of `use 5.010001`. Based on the changelog I'm guessing that wasn't intentional.

**Comment by autarch** [comment]
I'd also note that this means that anything that requires GLD _or_ MX::Getopt now fails to build on 5.10, which I discovered via some CI failures for Test-Class-Moose.

**Comment by rjbs** [comment]
It was _semi_ intentional.  My bundle now uses `package NAME VERSION` by default, which requires v5.12.0.  I didn't change the version by hand intentionally, but I did re-release to get other updates into the release, like a stated policy of "expect it to work on Perls this old."  The "this old" is "five years."  Perl v5.12.0 would be required even under what I call my "extremely long term support" policy, which is ten years.  v5.12 was released in 2010.

I do not plan to roll back the required version, but thanks for bringing this to my attention.
